### ISSUE TITLE
Peer review #1

### ISSUE THREAD

**Issue by vietng04** [shamayla38/EconomyLightCorrelation#1]
Summary
This research investigates the association between night-time light (NTL) intensity and GDP growth across countries between 1992 and 2001, using satellite data to provide an alternative proxy for economic development. By combining two large satellite datasets (DMSP/OLS and VIIRS), the study provides a globally consistent record of NTL intensity. It demonstrates how statistical capacity influences the strength of the association between NTL and GDP growth, arguing persuasively for the value of NTL data in regions with limited conventional economic measurements.

Strong positive points
- Innovative Use of NTL Data: The study proves that NTL is a useful indicator of economic development, particularly in areas with limited data.
- Methodological Clarity in Data Preparation: Detailed explanations of data extraction, cleaning, and aggregation promote transparency and reproducibility.
- Scripts: simulate data, data extraction, data cleaning, and aggregate data are included and well organized.

Critical improvements needed
- Missing Sections: The study's framework, methods, and interpretation depend on the Introduction, Model Description, and Discussion sections, all of which are absent from this publication.
- Raw and Clean Data: The repository does not contain the raw or cleaned data used in the analysis. Without them, reproducibility is hampered.
- Incomplete Results Section: Key findings, such as the exact correlation percentages ([X]% and [Y]%), are missing and must be completed.
- Limited Variability Exploration: While the correlation varies depending on statistical capacity, the study might delve deeper into why this variability exists and what it means.
- Overemphasis on Country-Level Analysis: Aggregating NTL data at the country level ignores intra-country differences, which could yield more nuanced insights.

Suggestions for improvements
- Add missing sections: Include a strong introduction to provide context and significance, a clear Model Description to explain the methodology, and a thorough Discussion to analyze findings and conclusions.
- Include raw and cleaned data. Upload raw and processed datasets into the repository to ensure transparency and repeatability.
- Add graphs: Missing graphs/ tables in the paper
- Finalize key findings: Replace the placeholders with real correlation percentages and highlight these findings in the abstract and results sections.
- Investigate Sub-National Trends: Include an examination of regional or urban-rural disparities to capture intra-country economic variances.
- Expand on Confounders: Discuss other elements that influence NTL, such as changes in lighting technology, and how these are compensated for.

Evaluation:
R/Python cited: 0/1 pts
Data cited: 1/1
Class paper: 1/1
LLM documentation: 0/1
Title: 0/2
Author, date, and repo: 2/2
Abstract: 3/4
Introduction: 0/4
Estimand: 0/1
Data: 4/10
Measurement: 0/4
Model: 0/10
Results: 0/10
Discussion: 0/10
Prose: 2/6
Cross-references: 0/1
Captions: 0/2
Graphs/tables/etc: 0/4
Surveys, sampling, and observational data appendix: 0/10
Referencing: 0/4
Commits: 1/2
Sketches: 0/2
Simulation: 0/4
Test:0/4
Parquet: 0/1
Reproducible workflow: 1/4
Enhancements: 0/4
Miscellaneous:0/3
Estimated overall mark:
14/112
The paper is incompleted.

**Comment by shamayla38** [comment]
Thanks
